# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23ccd72275dac56d55054ad7345635e4b07715fe6283d856c5266fc571ab9886f774acc71f1a12606f7a5b1a00bb4ae1ae0265c135ecde05cc0907a624088926

test:
  secret_key_base: 61771f4462854d75698ba6a07e2ea28713eeb3774a67739d165ae1ad5b625fd8bab9a24207c427b560acefb2859368eef6c07e4b49ea371d32a9df746fcd7677

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
